run:
	clear && symfony server:stop && symfony server:start --no-tls
	
stop:
	clear && symfony server:stop

dump:
	clear && php "./bin/console" server:dump
	
build:
	clear && yarn encore production --progress