########################################################################### 
# root/.symfony.local.yaml
# 
# https://symfony.com/doc/5.x/setup/symfony_server.html#configuring-workers
# 
# runs when "symfony server:start" runs
########################################################################### 
#
# ###> todos ###
#    (1)
#    set MERCURE_PUBLISHER_JWT_KEY=<PROVIDED VIA GLOBAL ENVIRONMENTS>
#    set MERCURE_SUBSCRIBER_JWT_KEY=<PROVIDED VIA GLOBAL ENVIRONMENTS>
#    Don't forget to reload cmd after setting a new environment
#    (2)
#    uncomment and set the correct --server-options-pfx
#    (3)
#    add 'devServer[options.watchFiles], devServer[options.static]' configuration to your 'webpack.config.js'
#    https://symfony.com/doc/5.x/frontend/encore/dev-server.html#live-reloading-when-changing-php-twig-files
#    
#    It'll be something like this:
#    Encore
#    
#      .configureDevServerOptions(options => {
#          options.static = {
#              watch: false
#          }
#          options.watchFiles = {
#              paths: ['src/**/*.php', 'templates/**/*'],
#          }
#      })

# ###< todos ###

workers:
    
    ###> 'webpack_dev_server' OR 'yarn_encore_dev_watch' ###
    # todo: https://symfony.com/doc/5.x/frontend/encore/dev-server.html#enabling-https-using-the-symfony-web-server
    # adds HMR (Hot Module Replacement)
    webpack_dev_server:
        cmd:
        -   yarn
        -   run
        -   'dev-server'
        -   '--port'
        -   8080
        -   '--client-logging'
        -   error
        -   '--hot'
        -   only
        ###> todo '--server-type' ###
        #
        # symfony server:start --no-tls   => 'http' (and use ngrok to provide an 'https' tunnel)
        # symfony server:start            => 'https'
        -   '--server-type'
        -   http
        #
        ###< todo '--server-type' ###

        ###> Symfony: generate ssl files "symfony server:ca:install" ###
        #
        #-   '--server-options-pfx'
        #-   '<ROOT>/.symfony5/certs/default.p12'
        #
        ###< Symfony: generate ssl files "symfony server:ca:install" ###
        -   '--live-reload'
        -   '--no-client-overlay'
        -   '--client-reconnect'
    #yarn_encore_dev_watch:
    #    cmd:
    #    -   yarn
    #    -   encore
    #    -   dev
    #    -   '--watch'
    ###< 'webpack_dev_server' OR 'yarn_encore_dev_watch' ###
    
    messenger_consume_all:
        cmd:
        -   php
        -   'bin/console'
        -   'messenger:consume'
        -   '--all'
        -   '--memory-limit=128M'
        watch:
        -   config
        -   src
        -   templates
        -   vendor
        
    mercure:
        cmd:
        -   './mercure.exe'
        -   'run'
        -   '--config'
        -   './dev.Caddyfile'