# clear && docker kill symfony && docker rm symfony && docker rmi symfony-symfony && docker compose up -d
services:
    symfony:
        build: .
        container_name: symfony
        restart: always
        volumes:
        -   'C:/Workspace/1_PROJECTS/SYMFONY/__SANDBOX__/drafts:/volumes/drafts'
        environment:
            r: '$rsync_to_remote_command'
            s: '$symfony_command'
            t: '$phpunit'